# This is a tchap-specific file, inspired from the one in matrix-react-sdk
name: Cypress End to End Tests

on:
    # Run this job when the "Build" job completes
    #workflow_run:
    #    workflows: ["Build"]
    #    types:
    #        - completed
    pull_request: {} # run for commits in PRs
    workflow_dispatch: # for running action manually

env:
    # Removing this makes the job break.
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
    CACHE_KEY: $(git rev-parse --short=12 HEAD)-${{ github.event.pull_request.number }}-${{ github.job }}

jobs:
    call-build-job:
        name: Build
        uses: ./.github/workflows/reusable-build.yaml
        with:
            CACHE_KEY: "$CACHE_KEY"

    cypress:
        name: Cypress
        #needs: call-build-job # run after call-build-job has succeeded
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get Node Version
              id: node_version
              run: echo ::set-output name=node_version::$(node -e 'console.log(require("./package.json").engines.node)')

            - name: Yarn cache
              uses: actions/setup-node@v3
              with:
                  cache: "yarn"
                  node-version: ${{ steps.node_version.outputs.node_version }}

            #####
            # Get build from artifact. Not needed since we called reusable-build.yml in the same workflow, we can reuse the files.
            #- name: Download build from artifact
            #  # use this action instead of actions/download-artifact because we need the "workflow" param
            #  uses: dawidd6/action-download-artifact@v2
            #  with:
            #      name: devbuild
            #      path: webapp
            #      run_id: ${{ github.event.workflow_run.id }} # I think this is the run_id of the workflow that triggered this workflow

            #- name: Install Dependencies
            #  run: "yarn install" # this is needed otherwise "cypress: not found". Can we do just yarn install cypress to go faster ?

            - name: Get build from cache
              uses: actions/cache@v3
              with:
                  path: ./webapp
                  key: "$CACHE_KEY"

            - name: Check presence of cache
              run: ls ./webapp

            - name: Install cypress
              run: yarn add cypress --dev #--ignore-scripts # ignore-scripts to avoid running postinstall

            - name: Run Cypress tests
              uses: cypress-io/github-action@v6.5.0
              with:
                  install: false # disable the default install, we already installed and built.

                  # Serve with 'npx serve', a simple static webserver, so that it starts quickly. The dev server is slow and messy to start.
                  start: "npx serve -p 8080 -L webapp"
                  # Note : 'wait-on' caused issues where localhost was not found by cypress. Be careful if you want to use it.

                  # From matrix-react-sdk : The built-in Electron runner seems to grind to a halt trying
                  # to run the tests, so use chrome.
                  browser: chrome
                  # headed: true # tchap uses headless, since we don't record videos.

                  command: "yarn test:cypress"
                  # Note : 'working-directory' changes pwd, for everything. If you use it you need to change relative paths for everything, it's tricky.
              env:
                  E2E_TEST_USER_EMAIL: ${{ secrets.E2E_TEST_USER_EMAIL }}
                  E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
                  E2E_TEST_USER_SECURITY_KEY: ${{ secrets.E2E_TEST_USER_SECURITY_KEY }}
                  E2E_TEST_USER_HOMESERVER_URL: "https://matrix.agent1.tchap.incubateur.net"
                  E2E_TEST_USER_HOMESERVER_SHORT: "agent1.tchap.incubateur.net"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # don't remember what this is for, can't hurt
