#Run a static analysis
#tchap modification : use "./scripts/layered.with.version.sh" instead of "./scripts/layered.sh"
name: Static Analysis
on:
    pull_request: {}
    push:
        branches: [develop, master]
    repository_dispatch:
        types: [element-web-notify]
env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  # Removing until we fix the crash :
  # Error: matrix-react-sdk/src/autocomplete/CommandProvider.tsx(38,24): error TS2589:
  # Type instantiation is excessively deep and possibly infinite.
  # ts_lint:
  #   name: "Typescript Syntax Check"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: 'yarn'

  #     - name: Install Dependencies
  #       run: "./scripts/layered.sh"

  #     - name: Typecheck
  #       run: "yarn run lint:types"

  # tchap : tchap does not use extensively i18n
  # i18n_lint:
  #   name: "i18n Check"
  #   uses: matrix-org/matrix-react-sdk/.github/workflows/i18n_check.yml@develop

    js_lint:
        name: "ESLint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"

            # Does not need branch matching as only analyses this layer
            - name: Install Deps
              run: "yarn install --pure-lockfile"

            - name: Run Linter
              run: "yarn run lint:js"

    style_lint:
        name: "Style Lint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                cache: "yarn"

            # Needs branch matching as it inherits .stylelintrc.js from matrix-react-sdk
            - name: Install Dependencies
              run: "./scripts/layered.with.version.sh"

            - name: Run Linter
              run: "yarn run lint:style"

  # tchap :  analyse:unused-exports does not work well with tchap customisations, it raises exception for "default export" not used
  # analyse_dead_code:
  #   name: "Analyse Dead Code"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: "yarn"

  #     - name: Install Deps
  #       run: "scripts/layered.with.version.sh"

  #     - name: Dead Code Analysis
  #       run: "yarn run analyse:unused-exports"
